Sawa 200 blob pictures
egecnr/SAWA-Backend pull request #19
Opened 2022-10-21 10:23 UTC by logoffro1

Use POSTMAN to test

2022-10-23 01:05 UTC, egecnr approved these changes

2022-10-23 01:06 UTC, egecnr requested changes

2022-10-23 01:06 UTC, egecnr commented on ShowerShow/Control/BlobStorageController.cs
> +        public async Task<HttpResponseData> UploadProfilePicture([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "user/{UserId:Guid}/profile/uploadpic")] HttpRequestData req, Guid UserId)
Dont forget to add auth bro

2022-10-23 01:09 UTC, egecnr commented on ShowerShow/Control/BlobStorageController.cs
> +                CloudBlobClient client = account.CreateCloudBlobClient();
Should you check whether the user exist or not? I'm not sure about the requirement of it

2022-10-24 00:25 UTC, logoffro1 commented
I added AUTH and checking for user, also added a DELETE endpoint and a default profile pic, in case the user doesn't have one

2022-10-24 00:30 UTC, egecnr commented
> I added AUTH and checking for user, also added a DELETE endpoint and a default profile pic, in case the user doesn't have one

GJ bro lets get this branch into dev

2022-10-24 00:30 UTC, egecnr approved these changes

2022-10-24 00:41 UTC, merged