Sawa 152 154 156 POST PUT GET - Preferences
egecnr/SAWA-Backend pull request #21
Opened 2022-10-21 23:18 UTC by fabiogiorgio

I forgot to perform a last push in the previous PR.

2022-10-25 17:20 UTC, egecnr commented on ShowerShow/Control/UserPreferencesController.cs
> +        [OpenApiOperation(operationId: "CreatePreferences", tags: new[] { "Preferences" })]
Add summary and description here. Also add summary and description to all your endpoints for more clearance.

2022-10-25 17:20 UTC, egecnr commented on ShowerShow/Control/UserPreferencesController.cs
> +        public async Task <HttpResponseData> CreateUserPreferences([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "user/{userId}/preferences")] HttpRequestData req)
Where is authorization????

2022-10-25 17:20 UTC, egecnr commented on ShowerShow/Control/UserPreferencesController.cs
> +        public async Task<HttpResponseData> GetUserPreferenceById([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "user/{userId:Guid}/preferences")] HttpRequestData req, Guid userId)
Authorization

2022-10-25 17:21 UTC, egecnr commented on ShowerShow/Control/UserPreferencesController.cs
> +            if (await _userService.CheckIfUserExistAndActive(userId))
You are checking if the user is active and then returning bad request.. Shouldnt you do the opposite?

2022-10-25 17:22 UTC, egecnr commented on ShowerShow/Model/Preferences.cs
>          public AvailableLanguages SelectedLanguage { get; set; } = AvailableLanguages.English;
Voices are in blob storage. Check in with cosmin to understand it better. this class needs a tiny update

2022-10-25 17:22 UTC, egecnr commented on ShowerShow/Model/AvailableWaterTypes.cs
> +        public enum AvailableWaterTypes { Liters, Gallons }
If frontend agreed to these enums its all good

2022-10-25 17:24 UTC, egecnr requested changes, later dismissed
I have commented the parts that need update. Also try to improve the controller class by using try catch. I have updated user and userfriend controllers you cans ee them for reference when I make the prs.

Some of the controllers have the wrong logic (such as update preference) make sure to thoroughly test your endpoints before you make your pr

2022-10-25 17:24 UTC, egecnr commented on ShowerShow/Model/AvailableWaterTypes.cs
> +        public enum AvailableWaterTypes { Liters, Gallons }
You can resolve this if you're in the same line with frontend

2022-10-25 17:25 UTC, egecnr commented on ShowerShow/Control/UserPreferencesController.cs
> +            if (await _userService.CheckIfUserExistAndActive(createPreferencesDTO.UserId))
For this case its correct you should only create pref if it doesnt exist this doesnt need to be fixed i think

2022-10-26 01:48 UTC, fabiogiorgio commented on ShowerShow/Control/UserPreferencesController.cs
> +            if (await _userService.CheckIfUserExistAndActive(createPreferencesDTO.UserId))
Ege said dont even have createpreference endpoint.only have a create method in repository

2022-10-26 03:03 UTC, logoffro1 approved these changes

2022-10-26 14:40 UTC, merged